#!/bin/bash

if [ "$1" == "--help" ]; then
    echo "Usage: gitupdate {commit message}"
    exit 0
fi

if [ -z "$1" ]; then
    echo "Error: missing argument"
    echo "Use --help for usage"
    exit 1
fi

git add .
git commit -m "$@"
git push origin main
